repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: check-docstring-first
    -   id: double-quote-string-fixer

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev:  v1.5.7
    hooks:
    -   id: autopep8